---
name: rule
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: sense
enabled: true
trigger:
  type: email.smtp.message
  parameters: {}
criteria:
  trigger:
    pattern: ishuwww084@gmail.com
    type: contains
action:
  ref: core.local
  parameters:
    cmd: echo "Hello from the sensor"
      	
 

